package com.dahua.nmea.utils

import android.location.Location
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.abs

class NmeaGenerator(private val outputFile: File) {
    
    private val fileWriter: FileWriter = FileWriter(outputFile, true)
    private var pointCount = 0
    private val dateFormat = SimpleDateFormat("ddMMyy", Locale.US)
    private val timeFormat = SimpleDateFormat("HHmmss.SSS", Locale.US)
    
    init {
        // Write header
        fileWriter.write("# NMEA GPS Data\n")
        fileWriter.write("# Generated by Dahua NMEA Recorder\n")
        fileWriter.write("# Format: NMEA 0183\n")
        fileWriter.flush()
    }
    
    fun addLocation(location: Location) {
        try {
            val time = Date(location.time)
            val currentTime = Date()
            
            android.util.Log.d("NmeaGenerator", "Writing point #$pointCount - GPS time: ${timeFormat.format(time)}, Current time: ${timeFormat.format(currentTime)}")
            
            // Generate GPRMC sentence (Recommended Minimum)
            val gprmc = generateGPRMC(location, time)
            fileWriter.write("$gprmc\n")
            
            // Generate GPGGA sentence (Global Positioning System Fix Data)
            val gpgga = generateGPGGA(location, time)
            fileWriter.write("$gpgga\n")
            
            fileWriter.flush()
            pointCount++
            
            android.util.Log.d("NmeaGenerator", "Point written successfully. Total points: $pointCount")
            
        } catch (e: Exception) {
            android.util.Log.e("NmeaGenerator", "Error writing point: ${e.message}")
            e.printStackTrace()
        }
    }
    
    private fun generateGPRMC(location: Location, time: Date): String {
        val timeStr = timeFormat.format(time)
        val dateStr = dateFormat.format(time)
        
        val lat = formatLatitude(location.latitude)
        val lon = formatLongitude(location.longitude)
        
        val speed = location.speed * 1.94384 // Convert m/s to knots
        val bearing = location.bearing
        
        val sentence = "GPRMC,$timeStr,A,$lat,$lon,%.1f,%.1f,$dateStr,,".format(
            Locale.US, speed, bearing
        )
        
        return "\$$sentence*${calculateChecksum(sentence)}"
    }
    
    private fun generateGPGGA(location: Location, time: Date): String {
        val timeStr = timeFormat.format(time)
        
        val lat = formatLatitude(location.latitude)
        val lon = formatLongitude(location.longitude)
        
        val quality = if (location.accuracy <= 10) "1" else "1" // GPS fix
        val numSatellites = "08" // Estimated
        val hdop = "%.1f".format(Locale.US, location.accuracy / 10)
        val altitude = "%.1f".format(Locale.US, location.altitude)
        
        val sentence = "GPGGA,$timeStr,$lat,$lon,$quality,$numSatellites,$hdop,$altitude,M,0.0,M,,"
        
        return "\$$sentence*${calculateChecksum(sentence)}"
    }
    
    private fun formatLatitude(latitude: Double): String {
        val direction = if (latitude >= 0) "N" else "S"
        val absLat = abs(latitude)
        val degrees = absLat.toInt()
        val minutes = (absLat - degrees) * 60
        
        return "%02d%07.4f,$direction".format(Locale.US, degrees, minutes)
    }
    
    private fun formatLongitude(longitude: Double): String {
        val direction = if (longitude >= 0) "E" else "W"
        val absLon = abs(longitude)
        val degrees = absLon.toInt()
        val minutes = (absLon - degrees) * 60
        
        return "%03d%07.4f,$direction".format(Locale.US, degrees, minutes)
    }
    
    private fun calculateChecksum(sentence: String): String {
        var checksum = 0
        for (char in sentence) {
            checksum = checksum xor char.code
        }
        return "%02X".format(checksum)
    }
    
    fun getPointCount(): Int = pointCount
    
    fun close() {
        try {
            fileWriter.write("# Total points: $pointCount\n")
            fileWriter.close()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    
    companion object {
        /**
         * Generate a single GPGGA sentence for a location
         * Useful for standalone GPS tracking without file management
         */
        fun generateGGA(location: Location): String {
            val timeFormat = SimpleDateFormat("HHmmss.SSS", Locale.US)
            val timeStr = timeFormat.format(Date(location.time))
            
            val lat = formatLatitudeStatic(location.latitude)
            val lon = formatLongitudeStatic(location.longitude)
            
            val quality = "1" // GPS fix
            val numSatellites = "08" // Estimated
            val hdop = "%.1f".format(Locale.US, location.accuracy / 10)
            val altitude = "%.1f".format(Locale.US, location.altitude)
            
            val sentence = "GPGGA,$timeStr,$lat,$lon,$quality,$numSatellites,$hdop,$altitude,M,0.0,M,,"
            
            return "\$$sentence*${calculateChecksumStatic(sentence)}"
        }
        
        private fun formatLatitudeStatic(latitude: Double): String {
            val direction = if (latitude >= 0) "N" else "S"
            val absLat = abs(latitude)
            val degrees = absLat.toInt()
            val minutes = (absLat - degrees) * 60
            
            return "%02d%07.4f,$direction".format(Locale.US, degrees, minutes)
        }
        
        private fun formatLongitudeStatic(longitude: Double): String {
            val direction = if (longitude >= 0) "E" else "W"
            val absLon = abs(longitude)
            val degrees = absLon.toInt()
            val minutes = (absLon - degrees) * 60
            
            return "%03d%07.4f,$direction".format(Locale.US, degrees, minutes)
        }
        
        private fun calculateChecksumStatic(sentence: String): String {
            var checksum = 0
            for (char in sentence) {
                checksum = checksum xor char.code
            }
            return "%02X".format(checksum)
        }
    }
}
